### ISSUE TITLE
Make cross_compile a pure Python package instead of ROS 2 package

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/cross_compile#102]
Now that cross_compile has ROS 1 support, it needs to be usable from all supported ROS distributions. Right now it is a ROS 2 package, which means it cannot be released into ROS Kinetic and Melodic as is.

It is desirable to convert it to a python package and release it through `pip` so that it is independent of ROS completely and installation steps are uniform independent of ROS distro used.

**Comment by emersonknapp** [comment]
Epic completed! https://pypi.org/project/ros-cross-compile/
