### ISSUE TITLE
Integrate GitHub Action for pure python package to build and test on OS matrix

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/cross_compile#110]
## Description
Instead of using our custom ROS2 CI GH Actions, set up this repo to use a CI Action for regular python packages.

## Related Issues
Part of Epic https://github.com/ros-tooling/cross_compile/issues/102
Depends on https://github.com/ros-tooling/cross_compile/issues/109

## Completion Criteria
* PRs are built with python action
* PRs are tested with python action
* Artifact of the build can be used in local virtualenv

## Implementation Notes/Suggestions
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by zmichaels11** [comment]
`launch ros sandbox` might be using: https://github.com/ros-tooling/action-pypi
