### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/cross_compile#112]
## Description
Perform the first release of this package to PyPI so that it can be pip installed.

## Related Issues
Part of Epic https://github.com/ros-tooling/cross_compile/issues/102
Depends on https://github.com/ros-tooling/cross_compile/issues/110
This is the final step for the Epic

## Completion Criteria
* [x] The package has the name `ros_cross_compile`
* [ ] I can `pip3 install ros_cross_compile` from production PyPI.
* [ ] The package is _not_ uploaded on every master push, only for explicit releases. For this ticket, this means a fully manual process is acceptable
* [ ] Write a runbook to describe how to release the package
* [ ] A nightly test installs cross_compile from PyPI and runs the e2e test (one each for test and production PyPI)

**Comment by zmichaels11** [comment]
GH Action trigger on tag to publish to PyPI
Already pushed to Test PyPI: https://test.pypi.org/project/cross-compile/
