### ISSUE TITLE
Time each step of the pipeline

### ISSUE THREAD

**Issue by darvg** [ros-tooling/cross_compile#207]
## Description

As a user, I can get the time each step of the pipeline takes to complete, so that I can determine what steps are bottlenecks to the compilation process

## Related Issues

Part of #205 
Related to #206 

## Completion Criteria

* Each stage is timed and the results are written to a uniquely named file in `cc_internal/` 

## Implementation Notes / Suggestions

none

## Testing Notes / Suggestions

* Unit tests for new functions/objects. 
* An end-to-end test should see if there is a time output for each stage of the cross compilation pipeline.

**Comment by emersonknapp** [comment]
Was resolved by #232
