### ISSUE TITLE
Report if an artifact is created per stage

### ISSUE THREAD

**Issue by darvg** [ros-tooling/cross_compile#208]
## Description

Getting the number of artifacts (Docker images) created per stage allows us to see which stages contribute to the total storage footprint of the tool, and why certain artifacts may contribute more than others.

## Related Issues

Part of #205 

## Completion Criteria

For each stage, log if an artifact is created and what its name is.

## Implementation Notes / Suggestions

None

## Testing Notes / Suggestions

For each stage, the accurate number of artifacts is output.

**Comment by emersonknapp** [comment]
Note from grooming - let's rewrite to mention specifically that we're reporting docker image creation and their size.
