### ISSUE TITLE
docker build fails due to rosdep issue

### ISSUE THREAD

**Issue by zmk5** [ros-tooling/cross_compile#21]
Hi,

I was following the guide located [here]() for cross-compiling and the command:

```
~$ docker build -t arm_ros2:latest -f ros2_ws/src/cross_compile/sysroot/Dockerfile_ubuntu_arm .
```

fails due on step 20/23 because of the following error:

```
ERROR: the following packages/stacks could not have their rosdep keys resolvedto system dependencies:
examples_rclcpp_minimal_composition: Cannot locate rosdep definition for ...
```
I was able to fix this and build properly by changing line 75 from `sysroot/Dockerfile_ubuntu_arm`:

```
RUN rosdep install --from-paths src \
    --ignore-src \
    --rosdistro crystal -y \
    --skip-keys "console_bridge \
        fastcdr \
        fastrtps \
        libopensplice67 \
        libopensplice69 \
        rti-connext-dds-5.3.1 \
        urdfdom_headers"
```
to this
```
RUN rosdep install --from-paths src \
    --ignore-src \
    --rosdistro dashing -y \
    --skip-keys "console_bridge \
        fastcdr \
        fastrtps \
        libopensplice67 \
        libopensplice69 \
        rti-connext-dds-5.3.1 \
        urdfdom_headers"
```

It seems that there is an issue with the crystal repositories didn't have specific packages, but the dashing one does. Hope this helps!

**Comment by pokitoz** [comment]
Do you mean https://index.ros.org/doc/ros2/Tutorials/Cross-compilation/ ? Your link is pointing to this issue.

I guess it's the right solution as you are probably getting `dashing` when cloning the `latest-release` branch from this line:
https://github.com/ros2/cross_compile/blob/c7bd1e4fb5a0b1d51d81169ab5a4d532042c937a/Dockerfile_cc_for_arm#L57

The script https://github.com/ros2/cross_compile/blob/master/sysroot/Dockerfile_ubuntu_arm hasn't been updated and still uses the crystal dependencies. I guess a long term fix would be to extract the ROS 2 version from the clone and feed it to the `rosdep` command.

Thanks for reporting !

**Comment by emersonknapp** [comment]
Closing as obsolete with the new workflow implemented. Can reopen if issue shows up again
