### ISSUE TITLE
docker.errors.ContainerError: Command '' in image 'ros_cross_compile:rosdep' returned non-zero exit status 2: See above ^

### ISSUE THREAD

**Issue by stanislavkuskov** [ros-tooling/cross_compile#270]
docker.errors.ContainerError: Command '' in image 'ros_cross_compile:rosdep' returned non-zero exit status 2: See above ^

with a base example: "ros_cross_compile foxy/ --arch aarch64 --os ubuntu --rosdistro foxy"
Same with dashing ros

**Comment by emersonknapp** [comment]
Hi! Thanks for opening this issue - can you provide more of the output, so that I can "See above ^"?

**Comment by emersonknapp** [comment]
@stanislavkuskov I'm going to close this issue for now - if this is still a problem and you can provide more information, please feel free to reopen it!
