### ISSUE TITLE
Tutorial uses file_talker repository that does not exist

### ISSUE THREAD

**Issue by improve100** [ros-tooling/cross_compile#291]
In README.md, the Tutorial specifies using the repository `https://github.com/ros-tooling/file_talker.git` but this repository doesn't seem to exist.

**Comment by emersonknapp** [comment]
Next time it would help if you added a little more information to your ticket - but I eventually realized what you meant. You're right that the file_talker moved, and it seems that the redirect expired, or the repository that it moved to was archived/deleted.

The resolution here is to update the tutorial to suggest a more supported package - I think a good choice would be to build one of the packages from `demo_nodes_cpp` - https://github.com/ros2/demos/tree/master/demo_nodes_cpp. I won't be able to get to this immediately, but thank you for bringing it up!
