### ISSUE TITLE
Error building due to ROS GPG key unavailable

### ISSUE THREAD

**Issue by sanatmharolkar** [ros-tooling/cross_compile#328]
The ROS packages public key F42ED6FBAB17C654 is no longer available due to a recent incident, it has been replaced with a new key. The package ros_cross_compile is still trying to download the packages in Docker using the old key. The build is failing due to this.

```
INFO:Docker Client:Err:4 http://packages.ros.org/ros2/ubuntu buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
INFO:Docker Client:Reading package lists...
INFO:Docker Client:W
INFO:Docker Client:: 
INFO:Docker Client:GPG error: http://packages.ros.org/ros2/ubuntu buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
INFO:Docker Client:

INFO:Docker Client:E: The repository 'http://packages.ros.org/ros2/ubuntu buster InRelease' is not signed.

ERROR:Docker Client:Error building Docker image. The follow error was caught:
The command '/bin/bash -c apt-get update && apt-get install --no-install-recommends -y       build-essential       cmake       python3-colcon-common-extensions       python3-colcon-mixin       python3-de
v       python3-pip     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by TSC21** [comment]
That was already fixed in https://github.com/ros-tooling/cross_compile/pull/317. What version of thd tool are you using?

**Comment by sanatmharolkar** [comment]
I installed using "pip3 install ros_cross_compile". It is version 0.8.0

**Comment by TSC21** [comment]
The above PR changes already include the update to whwre the keys are being fetched from. What ROS distro, arch and OS are you trying this against?

**Comment by sanatmharolkar** [comment]
**Target:**
OS - Debian (Buster)
Arch - armhf
Distro - Foxy

**Host:**
OS - Ubuntu 20.04
Arch - amd64

**Comment by TSC21** [comment]
> **Target:**
> OS - Debian (Buster)
> Arch - armhf
> Distro - Foxy
> 
> **Host:**
> OS - Ubuntu 20.04
> Arch - amd64

Foxy is not available in Debian Buster for `armhf` - https://github.com/ros-tooling/cross_compile/blob/master/test/run_e2e_test.sh#L91.

**Comment by sanatmharolkar** [comment]
Oh. I guess I'll have to do the compilation manually. Thanks.
