### ISSUE TITLE
Update to match the REP-2000

### ISSUE THREAD

**Issue by flochre** [ros-tooling/cross_compile#368]
## Description

Update the code to match the updated REP-2000

## Related Issues

NA

## Completion Criteria

Release from REP-2000 are usable

## Implementation Notes / Suggestions

Update readme and platform.py

## Testing Notes / Suggestions

changes are minor and the testing could be to start the process of building the docker with each compatible ROS distros
Successfull test would be passing the check and not getting the message : 'Unknown target architecture "{}" specified'.format(arch)

see : https://github.com/ros-tooling/cross_compile/blob/master/ros_cross_compile/platform.py#L89

**Comment by MichaelOrlov** [comment]
- Closing as done in #372
