### ISSUE TITLE
Make a new release before we archive cross_compile repo

### ISSUE THREAD

**Issue by MichaelOrlov** [ros-tooling/cross_compile#378]
## Description
@emersonknapp Could you please make a new release before we archive this `cross_compile` repo?

**Comment by emersonknapp** [comment]
Done
https://github.com/ros-tooling/cross_compile/releases/tag/0.10.0
https://pypi.org/project/ros-cross-compile/0.10.0/

**Comment by MichaelOrlov** [comment]
@emersonknapp Thanks for doing this release, much appreciated.

I am considering removing `dependabot.yaml` file from `.github` folder and also remove daily running schedule for tests before archiving this repo and making it read only.

Do yo think it make sense?

**Comment by emersonknapp** [comment]
Yes, this makes sense. Best to disable any scheduled infrastructure
