### ISSUE TITLE
version points to master in cross_compile.repos on dashing-devel branch

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/cross_compile#46]
[Link to repos file](https://raw.githubusercontent.com/ros-tooling/cross_compile/dashing-devel/cross_compile.repos)

If you are using the distro-specific branch of the cross_compile tool, it should target that same distro in the repos file that it uses to check out code.

For branch `dashing-devel`
Value is: `version: master`
Should be: `version:dashing-devel`

**Comment by emersonknapp** [comment]
Closing this issue in favor of work towards https://github.com/ros-tooling/cross_compile/issues/102 - we'd rather spend the time making this tool work outside of ROS, where we will delete the .repos file and distro-specific branches on this repo
