### ISSUE TITLE
Document why we need symlinks in the Docker file

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/cross_compile#49]
Could you document why it's needed?

_Originally posted by @thomas-moulard in https://github.com/ros-tooling/cross_compile/pull/45/review_comment/create_

**Comment by zmichaels11** [comment]
@zmichaels11 check if this is still needed, otherwise close

**Comment by thomas-moulard** [comment]
symlink is not in the Dockerfile anymore so very likely to be irrelevant now. @piraka9011 @zmichaels11 please feel free to reopen as needed.
