### ISSUE TITLE
Pseudo-randomize container names to distinguish them from each other

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/cross_compile#64]
Copied from the aws-ros-dev fork:

-----

The script produces a docker image and starts a container with a fixed name. If the container is not stopped, all subsequent script executions will try to start the old container and produce incorrect results.

This can be mitigated by adding a fixed length random string at the end of the current container name, to distinguish between different invocations of the script.

### Resources

[Issue #27](https://github.com/aws-ros-dev/cross_compile/issues/27)

**Comment by emersonknapp** [comment]
Closing as no longer relevant - in the tool as it is right now:
* The majority of functionality happens in a `docker build` which does not have a name
* The final build is exported via a `docker run` with no arguments, so the name is chosen by docker e.g. `frivolous_einstein`
