### ISSUE TITLE
Add supported cross compile targets to README

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/cross_compile#99]
### Description
Supported target platforms should be easily located in the README doc so users of Cross Compile can quickly know what is supported.

### Test Plan
* N/A

### Documentation
* Update `README.md` to display supported cross compile targets

### Release Plan
* check in PR

### Acceptance Criteria
* [ ] `README.md` is updated
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

### Resources

**Comment by prajakta-gokhale** [comment]
This will be covered in https://github.com/ros-tooling/cross_compile/issues/69.

**Comment by emersonknapp** [comment]
To support this, I am making minor changes to the `sysroot_compiler` to centralize supported targets in one place (in addition to the README update)
